## Q1

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
from sklearn import datasets
dataset=datasets.load_iris()

In [3]:
X=dataset['data']
y=dataset['target']

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
classifier=KNeighborsClassifier(n_neighbors=5,algorithm='auto')
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [8]:
y_pred=classifier.predict(X_test)

In [9]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [10]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0  0]
 [ 0 15  1]
 [ 0  0 15]]
0.98
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.94      0.97        16
           2       0.94      1.00      0.97        15

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



 ## Q2

In [14]:

from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
X=housing['data']
y=housing['target']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [17]:
from sklearn.neighbors import KNeighborsRegressor

In [18]:
regressor=KNeighborsRegressor(n_neighbors=6,algorithm='auto')
regressor.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=6)

In [19]:
y_pred=regressor.predict(X_test)

In [20]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [21]:
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

0.13264902507249854
0.8299419211195929
1.1558248101134174


## Q3

In [25]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

dataset=datasets.load_iris()
X = dataset['data']
y = dataset['target']

k_values = list(range(1, 31)) 

param_grid = {'n_neighbors': k_values}

knn_classifier = KNeighborsClassifier()

grid_search = GridSearchCV(knn_classifier, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X, y)

best_k = grid_search.best_params_['n_neighbors']
best_score = grid_search.best_score_

print("Optimal K:", best_k)
print("Cross-Validation Accuracy:", best_score)

Optimal K: 6
Cross-Validation Accuracy: 0.9800000000000001


## Q4

In [31]:
from sklearn.preprocessing import StandardScaler

from sklearn.datasets import fetch_california_housing
dataset = fetch_california_housing()
X = pd.DataFrame(dataset.data, columns=dataset.feature_names)
y = pd.Series(dataset.target, name="MEDV")

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

k = 6  
knn_regressor = KNeighborsRegressor(n_neighbors=k)
knn_regressor.fit(X_train_scaled, y_train)

y_pred = knn_regressor.predict(X_test_scaled)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)


Mean Squared Error: 0.4290973699787851
R-squared: 0.6725469856328306


## Q5|

In [32]:
data = load_iris()
X = data.data
y = data.target

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

k = 69 
knn_classifier = KNeighborsClassifier(n_neighbors=k, weights='distance')
knn_classifier.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=69, weights='distance')

In [42]:
y_pred = knn_classifier.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 1.0


## Q6

In [45]:
def standardize_features(X_train, X_test):
   
    scaler = StandardScaler()

    X_train_scaled = scaler.fit_transform(X_train)

    X_test_scaled = scaler.transform(X_test)

    return X_train_scaled, X_test_scaled

X_train_scaled, X_test_scaled = standardize_features(X_train, X_test)

k = 5 
knn_classifier = KNeighborsClassifier(n_neighbors=k)
knn_classifier.fit(X_train_scaled, y_train)

y_pred = knn_classifier.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)



Accuracy: 1.0


## Q7

In [46]:
import math

def euclidean_distance(point1, point2):
   
    if len(point1) != len(point2):
        raise ValueError("Both points must have the same number of dimensions.")

    squared_distance = sum((x - y) ** 2 for x, y in zip(point1, point2))
    distance = math.sqrt(squared_distance)
    
    return distance

In [47]:
point1 = (1, 2)
point2 = (4, 6)

distance = euclidean_distance(point1, point2)
print("Euclidean Distance:", distance)

Euclidean Distance: 5.0


## Q8

In [ ]:
def manhattan_distance(point1, point2):
    if len(point1) != len(point2):
        raise ValueError("Both points must have the same number of dimensions.")

    distance = sum(abs(x - y) for x, y in zip(point1, point2))
    
    return distance
